---
title: "Extract environmental data to BNLL occurrences"
author: "Maxwell Pepperdine"
format: html
editor: visual
date: last-modified
editor_options: 
  chunk_output_type: console
---

## Overview

This script extracts environmental data to BNLL occurrence points for use in MaxEnt modeling. The environmental data includes:

- BCM climate (AET, PPT)
- gSSURGO soil data (pH, % clay, EC)
- Slope

```{r}
rm(list=ls())
```

## Load packages

```{r}
library(terra)      # for raster processing
library(tidyverse)  # always
library(sf)         # for spatial data processing
```

## Load data

#### Environmental rasters

```{r}
# load all env rasters
env_rasters <- rast(list.files(here("data/intermediate/misc/habitat_suitability/env_predictors/baseline/keep_NAs"), 
                               pattern = ".tif$", 
                               full.names = TRUE))
plot(env_rasters)
```

#### BNLL occurrences

```{r}
# load occurrence points
bnll_occ <- read_csv("data/raw/occurrence_points/bnll/wallace/bnll_occur_wallace.csv")

# convert occ points to SpatVector
bnll_occ_vect <- vect(bnll_occ, 
                      geom = c("longitude", "latitude"), 
                      crs = "EPSG:4326")

# make sure crs matches env rasters
bnll_occ_vect <- project(bnll_occ_vect, crs(env_rasters))
```

## Extract environmental data to occurrence points

```{r}
# extract env data to occ points
bnll_occ_env <- terra::extract(env_rasters, bnll_occ_vect, 
                               bind = TRUE)

# set as sf object
bnll_occ_env_sf <- st_as_sf(bnll_occ_env, 
                            coords = c("longitude", "latitude")) %>% 
  select(-gbif_id, -basis_of_record, -institution_code)

# extract geometry columns as lat/lon
bnll_occ_env_df <- bnll_occ_env_sf %>% 
  mutate(longitude = st_coordinates(bnll_occ_env_sf)[,1],
         latitude = st_coordinates(bnll_occ_env_sf)[,2], 
         .before = "aet1991_2020_ave") %>%
  st_drop_geometry()
```




















